Add files via upload
if you encountered with error like 
ERROR in ./resources/js/components/Example.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\xampp\htdocs\amit\resources\js\components\Example.jsx: Support 

then follow the step
step-1 : run the command  :     npm install --save-dev @babel/preset-react
step-2 : create a file named as '.babelrc' on root of the project and add below script in it:
{
  "presets": ["@babel/preset-react"]
}
step-3 : run command : npm run dev
step-4 : place the build folder inside the public directoy if you find any error related with missing build/manifest.json